namespace ProdUI.Bridge.NativePatterns
{
    /// <summary>
    /// http://msdn.microsoft.com/en-us/library/windows/desktop/bb760435(v=VS.85).aspx
    /// </summary>
    internal enum ToolbarMessages
    {
        WM_USER = 0x0400,
        TB_ADDBUTTONS = (WM_USER + 68),
        TB_ADDSTRING = (WM_USER + 77),
        TB_AUTOSIZE = (WM_USER + 33),
        TB_BUTTONSTRUCTSIZE = (WM_USER + 30),
        TB_CHANGEBITMAP = (WM_USER + 43),
        TB_CUSTOMIZE = (WM_USER + 27),
        TB_GETANCHORHIGHLIGHT = (WM_USER + 74),
        TB_GETBITMAP = (WM_USER + 44),
        TB_GETBUTTONINFO = (WM_USER + 63),
        TB_GETBUTTONSIZE = (WM_USER + 58),
        TB_GETBUTTONTEXT = (WM_USER + 75),
        TB_GETDISABLEDIMAGELIST = (WM_USER + 55),
        TB_GETEXTENDEDSTYLE = (WM_USER + 85),
        TB_GETHOTIMAGELIST = (WM_USER + 53),
        TB_GETHOTITEM = (WM_USER + 71),
        TB_GETIDEALSIZE = (WM_USER + 99),
        TB_GETIMAGELIST = (WM_USER + 49),
        TB_GETIMAGELISTCOUNT = (WM_USER + 98),
        TB_GETINSERTMARK = (WM_USER + 79),
        TB_GETINSERTMARKCOLOR = (WM_USER + 89),
        TB_GETITEMDROPDOWNRECT = (WM_USER + 103),
        TB_GETITEMRECT = (WM_USER + 29),
        TB_GETMAXSIZE = (WM_USER + 83),
        TB_GETOBJECT = (WM_USER + 62),
        TB_GETPADDING = (WM_USER + 86),
        TB_GETPRESSEDIMAGELIST = (WM_USER + 105),
        TB_GETRECT = (WM_USER + 51),
        TB_GETROWS = (WM_USER + 40),
        TB_GETSTRING = (WM_USER + 91),
        TB_GETSTYLE = (WM_USER + 57),
        TB_GETTEXTROWS = (WM_USER + 61),
        TB_GETTOOLTIPS = (WM_USER + 35),
        TB_HITTEST = (WM_USER + 69),
        TB_INSERTBUTTON = (WM_USER + 67),
        TB_INSERTMARKHITTEST = (WM_USER + 81),
        TB_LOADIMAGES = (WM_USER + 50),
        TB_MOVEBUTTON = (WM_USER + 82),
        TB_REPLACEBITMAP = (WM_USER + 46),
        TB_SAVERESTORE = (WM_USER + 76),
        TB_SETANCHORHIGHLIGHT = (WM_USER + 73),
        TB_SETBITMAPSIZE = (WM_USER + 32),
        TB_SETBUTTONINFO = (WM_USER + 64),
        TB_SETBUTTONSIZE = (WM_USER + 31),
        TB_SETBUTTONWIDTH = (WM_USER + 59),
        TB_SETCMDID = (WM_USER + 42),
        TB_SETDISABLEDIMAGELIST = (WM_USER + 54),
        TB_SETEXTENDEDSTYLE = (WM_USER + 84),
        TB_SETHOTIMAGELIST = (WM_USER + 52),
        TB_SETHOTITEM = (WM_USER + 72),
        TB_SETHOTITEM2 = (WM_USER + 94),
        TB_SETIMAGELIST = (WM_USER + 48),
        TB_SETINDENT = (WM_USER + 47),
        TB_SETINSERTMARK = (WM_USER + 80),
        TB_SETINSERTMARKCOLOR = (WM_USER + 88),
        TB_SETLISTGAP = (WM_USER + 96),
        TB_SETMAXTEXTROWS = (WM_USER + 60),
        TB_SETPADDING = (WM_USER + 87),
        TB_SETPARENT = (WM_USER + 37),
        TB_SETPRESSEDIMAGELIST = (WM_USER + 104),
        TB_SETROWS = (WM_USER + 39),
        TB_SETSTYLE = (WM_USER + 56),
        TB_SETTOOLTIPS = (WM_USER + 36)
    }
}