namespace ProdUI.Bridge.NativePatterns
{
    /// <summary>
    /// http://msdn.microsoft.com/en-us/library/windows/desktop/bb787605(v=VS.85).aspx
    /// </summary>
    internal enum RicheditMessages
    {
        WM_USER = 0x0400,
        EM_AUTOURLDETECT = (WM_USER + 91),
        EM_CANPASTE = (WM_USER + 50),
        EM_CANREDO = (WM_USER + 85),
        EM_CHARFROMPOS = (WM_USER + 39),
        EM_DISPLAYBAND = (WM_USER + 51),
        EM_EXGETSEL = (WM_USER + 52),
        EM_EXLIMITTEXT = (WM_USER + 53),
        EM_EXLINEFROMCHAR = (WM_USER + 54),
        EM_EXSETSEL = (WM_USER + 55),
        EM_FINDTEXT = (WM_USER + 123),
        EM_FINDTEXTEX = (WM_USER + 124),
        EM_FINDWORDBREAK = (WM_USER + 76),
        EM_FORMATRANGE = (WM_USER + 57),
        EM_GETAUTOURLDETECT = (WM_USER + 92),
        EM_GETCHARFORMAT = (WM_USER + 58),
        EM_GETEDITSTYLE = (WM_USER + 205),
        EM_GETEVENTMASK = (WM_USER + 59),
        EM_GETIMEMODEBIAS = (WM_USER + 127),
        EM_GETLIMITTEXT = (WM_USER + 37),
        EM_GETOLEINTERFACE = (WM_USER + 60),
        EM_GETOPTIONS = (WM_USER + 78),
        EM_GETPARAFORMAT = (WM_USER + 61),
        EM_GETREDONAME = (WM_USER + 87),
        EM_GETSELTEXT = (WM_USER + 62),
        EM_GETTEXTEX = (WM_USER + 94),
        EM_GETTEXTLENGTHEX = (WM_USER + 95),
        EM_GETTEXTMODE = (WM_USER + 90),
        EM_GETTEXTRANGE = (WM_USER + 75),
        EM_GETUNDONAME = (WM_USER + 86),
        EM_GETWORDBREAKPROCEX = (WM_USER + 80),
        EM_HIDESELECTION = (WM_USER + 63),
        EM_PASTESPECIAL = (WM_USER + 64),
        EM_POSFROMCHAR = (WM_USER + 38),
        EM_RECONVERSION = (WM_USER + 125),
        EM_REDO = (WM_USER + 84),
        EM_REQUESTRESIZE = (WM_USER + 65),
        EM_SCROLLCARET = (WM_USER + 49),
        EM_SELECTIONTYPE = (WM_USER + 66),
        EM_SETBKGNDCOLOR = (WM_USER + 67),
        EM_SETCHARFORMAT = (WM_USER + 68),
        EM_SETEDITSTYLE = (WM_USER + 204),
        EM_SETEVENTMASK = (WM_USER + 69),
        EM_SETIMEMODEBIAS = (WM_USER + 126),
        EM_SETOLECALLBACK = (WM_USER + 70),
        EM_SETOPTIONS = (WM_USER + 77),
        EM_SETPALETTE = (WM_USER + 93),
        EM_SETPARAFORMAT = (WM_USER + 71),
        EM_SETTARGETDEVICE = (WM_USER + 72),
        EM_SETTEXTEX = (WM_USER + 97),
        EM_SETTEXTMODE = (WM_USER + 89),
        EM_SETUNDOLIMIT = (WM_USER + 82),
        EM_SETWORDBREAKPROCEX = (WM_USER + 81),
        EM_SHOWSCROLLBAR = (WM_USER + 96),
        EM_STOPGROUPTYPING = (WM_USER + 88),
        EM_STREAMIN = (WM_USER + 73),
        EM_STREAMOUT = (WM_USER + 74)
    }
}